### ISSUE TITLE
Duplicated ensembl gene name

### ISSUE THREAD

**Issue by ryrl9703** [CCIVR/ccivr#1]
The results of the ccivr have duplicated ensemble gene name with the same position on chr, while the ensembl is not duplicate in the input file. Why?

**Comment by CCIVR** [comment]
Hello ryrl9703,

Thanks for your comment.
As far as we understand, you meant that there were two gene names on the same row in the results file, didn't you?
If so, here is the answer to your concern.
The output file of CCIVR contains a list of cisNATs pairs, including a target gene on the right and its cisNATs on the left.
I imagine you were confused because it looked like duplicate gene names with the same position on the chromosome.

I hope this helps.

Team CCIVR
